version: "3.7"

# For local development, only database is running
#
# docker-compose up -d
#

# https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/docker-compose.dev.yml

services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
    env_file:
      - .env.local
    restart: always

  
  database:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    networks:
      - my_network

volumes:
  database_data:

networks:
  my_network:
    external: true